Repository opensearch-project/search-processor, pull requests merged in 2022-12, with the labels that each got.

#41 Fix codecov after repo renaming
  DEVELOPER_GUIDE.md
  README.md
  RELEVANCE.md
  build.gradle
  helpers/search_processing_kendra_quickstart.sh
  settings.gradle
Labels: bug, enhancement

#51 Remove DCO config and update PR template link
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/create-documentation-issue.yml
  .github/workflows/dco.yml
Labels: configuration error, backport 2.x

#58 Updating README.md to talk more about Search Query & Request Transfor…
  README.md
Labels: documentation
