Repository opensearch-project/search-processor, pull requests merged in 2023-07, with the labels that each got.

#152 Add ignoreFailure and pipelineContext
  src/main/java/org/opensearch/search/relevance/SearchRelevancePlugin.java
  src/main/java/org/opensearch/search/relevance/configuration/ConfigurationUtils.java
  src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/pipeline/KendraRankingResponseProcessor.java
  src/main/java/org/opensearch/search/relevance/transformer/personalizeintelligentranking/PersonalizeRankingResponseProcessor.java
  src/test/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/pipeline/KendraRankingResponseProcessorTests.java
  src/test/java/org/opensearch/search/relevance/transformer/personalizeintelligentranking/PersonalizeResponseProcessorTests.java
Labels: backport 2.x, v2.9.0

#161 [Backport][2.x] Fetch index settings asynchronously (#135)
  src/main/java/org/opensearch/search/relevance/actionfilter/SearchActionFilter.java
  src/main/java/org/opensearch/search/relevance/client/OpenSearchClient.java
  src/main/java/org/opensearch/search/relevance/configuration/ConfigurationUtils.java
  src/test/java/org/opensearch/search/relevance/actionfilter/SearchActionFilterTests.java
  src/yamlRestTest/resources/rest-api-spec/test/10_basic.yml
Labels: backport 2.x, backport 2.6, backport 2.8

#168 [Refactor] Update Imports to Match OpenSearch
  src/main/java/org/opensearch/search/relevance/SearchRelevancePlugin.java
  src/main/java/org/opensearch/search/relevance/actionfilter/SearchActionFilter.java
  src/main/java/org/opensearch/search/relevance/configuration/ResultTransformerConfigurationFactory.java
  src/main/java/org/opensearch/search/relevance/configuration/SearchConfigurationExtBuilder.java
  src/main/java/org/opensearch/search/relevance/configuration/TransformerConfiguration.java
  src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/client/KendraClientSettings.java
  src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/configuration/KendraIntelligentRankerSettings.java
  src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/configuration/KendraIntelligentRankingConfiguration.java
  src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/configuration/KendraIntelligentRankingConfigurationFactory.java
  src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/model/KendraIntelligentRankingException.java
  src/main/java/org/opensearch/search/relevance/transformer/personalizeintelligentranking/client/PersonalizeClientSettings.java
  src/main/java/org/opensearch/search/relevance/transformer/personalizeintelligentranking/requestparameter/PersonalizeRequestParameters.java
  src/main/java/org/opensearch/search/relevance/transformer/personalizeintelligentranking/requestparameter/PersonalizeRequestParametersExtBuilder.java
  src/test/java/org/opensearch/search/relevance/actionfilter/SearchActionFilterTests.java
  src/test/java/org/opensearch/search/relevance/configuration/SearchConfigurationExtBuilderTests.java
  src/test/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/KendraIntelligentRankerTests.java
  src/test/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/configuration/KendraIntelligentRankingConfigurationTests.java
  src/test/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/pipeline/KendraRankingResponseProcessorTests.java
  src/test/java/org/opensearch/search/relevance/transformer/personalizeintelligentranking/requestparameter/PersonalizeRequestParametersExtBuilderTests.java
  src/test/java/org/opensearch/search/relevance/transformer/personalizeintelligentranking/utils/SearchTestUtil.java
Labels: maintenance

#169 Pass environment setting to personalized setting while cluster is up
  src/main/java/org/opensearch/search/relevance/SearchRelevancePlugin.java
  src/main/java/org/opensearch/search/relevance/transformer/personalizeintelligentranking/client/PersonalizeClientSettings.java
  src/test/java/org/opensearch/search/relevance/transformer/personalizeintelligentranking/client/PersonalizeClientSettingsTests.java
Labels: backport 2.x, backport 2.9

#173 Fix AccessControlException while creating client configuration for Personalize client
  src/main/java/org/opensearch/search/relevance/transformer/personalizeintelligentranking/client/PersonalizeClient.java
Labels: backport 2.x, backport 2.9
